###
POST http://127.0.0.1:3000/users/create
Content-Type: application/json

{
    "name": "YOS2",
    "email": "pruebas",
    "password": "durisimohermano"
}
###
POST http://127.0.0.1:3000/product/create
Content-Type: application/json

{
    "name": "pruebawaza3",
    "stock": 20,
    "price": 35,
    "description": "Pulsera de cuero bien mamada",
    "category": "Pulsera"
}

###
GET http://127.0.0.1:3000/products