###
POST http://127.0.0.1:3000/users/create
Content-Type: application/json

{
    "name": "YOS2",
    "email": "pruebas",
    "password": "durisimohermano"
}
###
POST http://127.0.0.1:3000/products/create
Content-Type: application/json

{
    "name": "pruebawaza4",
    "stock": 20,
    "price": 35,
    "description": "Pulsera de cuero bien mamada",
    "category": "Pulsera"
}

### OBTIENE LA LISTA DE LOS PRODUCTOS
GET http://127.0.0.1:3000/products


### OBTIENE PRODUCTOS POR ID
GET http://127.0.0.1:3000/products/6792605c67ea5a659861446d

###
PATCH http://127.0.0.1:3000/products/6792605c67ea5a659861446d
Content-Type: application/json

{
    "name": "pruebawaza}}}adas4",
    "stock": 80,
    "price": 35,
    "description": "Pulsera de cufasfsafasero bien mamada",
    "category": "collar"
}